// <auto-generated />
using Infra.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Infra.Repository.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20180522015121_Migration-A1")]
    partial class MigrationA1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("custumer","dbo");
                });

            modelBuilder.Entity("Domain.Entities.Models.Customer", b =>
                {
                    b.OwnsOne("Domain.Entities.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CustomerId");

                            b1.Property<decimal>("Value")
                                .HasColumnName("Cpf");

                            b1.ToTable("custumer","dbo");

                            b1.HasOne("Domain.Entities.Models.Customer")
                                .WithOne("Cpf")
                                .HasForeignKey("Domain.Entities.ValueObjects.Cpf", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Domain.Entities.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasColumnType("varchar(30)");

                            b1.ToTable("custumer","dbo");

                            b1.HasOne("Domain.Entities.Models.Customer")
                                .WithOne("Email")
                                .HasForeignKey("Domain.Entities.ValueObjects.Email", "CustomerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
